# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d57b2443688ed10d532caee02ecfa7a6684cecb396d68544dc2a2f6656e7aa2c673189120ce3c337e6b1d84b6e581bb09c0cbec809f858d82f0ee0b8aa78892

test:
  secret_key_base: 9499bfcbbd018c75ef12e13f31e6aa04b503ef7355f377b41d0b8afcb635b7715e0ed41c9aa6419ee6e2e95b0c581ad3fdd10713751b3073bda67e886c37b5a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
