# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60d198fdf0259f8bd7e85ba702f8dd9af2889aafe6e448b01477163c0b9ae9f5f76ca60532308460d4677ecb93c0e7bcf0ee197ab0e6751fdeb06ea53a8870c5

test:
  secret_key_base: 320c2ab71edb53dda39212a8d1e37323d1b0facd2817040712e0ffa629f0e6908660251a04cc88bcbde9fff4cc25e4d118505f0df500379c7df656a9624013ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
