# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccc4175dd15e52b9e779257d95984b09bba473d40ebce5c8895e2fbcf28eadd71fc6dc69ab38ecc206ce26928a51b0aebbe4d9335abb4296bf6257d923d6b0be

test:
  secret_key_base: 58ddc1a805e57ddceb2bf92bd2e5c5213e29ac10e29ae475a5e4c4840d01278310548d6396053dfd04c2a30925e93d810649de4eacb3f37267c7fe202be57c63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
